services:

  frog-db:
    image: postgres
    container_name: frog-cafe-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: 'GMT+3'
      PGTZ: 'GMT+3'
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ~/frog_cafe_data/db:/var/lib/postgresql/data:rw
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 60s
      timeout: 3s
      retries: 5

