version: '3.9'

services:

  frog-db:
    image: postgres
    container_name: frog-cafe-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: 'GMT+3'
      PGTZ: 'GMT+3'
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ~/frog_cafe_data/db:/var/lib/postgresql/data:rw
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 60s
      timeout: 3s
      retries: 5

